#!/bin/bash
DOMAIN=${1:-magento2.test}
VERSION=${2:-2.4.0}
EDITION=${3:-community}
BRANCH=${4:-master}
GITHUB_USER=${5:-markshust}

URL="https://raw.githubusercontent.com/${GITHUB_USER}/docker-magento/${BRANCH}/lib/template"
echo Downloading $URL ...
curl -v $URL | bash
bin/download $VERSION $EDITION

echo "Your system password has been requested to add an entry to /etc/hosts..."
echo "127.0.0.1 ::1 $DOMAIN" | sudo tee -a /etc/hosts

bin/setup $DOMAIN
